### ISSUE TITLE
cant change anything about mouse!!

### ISSUE THREAD

**Issue by ahaarij** [stickoking/razer-macos#17]
i have a deathadder v2 and nothing works, other than using it for the first time and now its set to reactive, but when i try to change it, nothing happens and it stays at reactive, can this pleease be changed? and can you also tell me the dir where i can change it myself if not?

**Comment by stickoking** [comment]
Please share some screenshots, please click on the razer-macos menu click on state-manager then click on current device state and share a screenshot.

**Comment by ahaarij** [comment]
<img width="262" alt="Screenshot 2024-03-03 at 12 44 09 PM" src="https://github.com/stickoking/razer-macos/assets/141050074/2a801ef0-c6a0-44c5-9556-573dcb0f2720">

**Comment by ahaarij** [comment]
it says i chose spectrum, which is true, but it doesnt show on my mouse. on my mouse it still shows im on reactive red, any idea why?

**Comment by stickoking** [comment]
In The razer-macos menu can you click on clear all settings then click on state manager once inside in the states tab in the drop down select all lights off. Confirm the lights of your mouse is being turned off once off can you try to set it to spectrum again.

**Comment by ahaarij** [comment]
okay, i just did what you said, when i got to the states tab and selected all lights off, it didnt work, and neither did the steps after it, throughhout the whole process it remained at reactive red

**Comment by stickoking** [comment]
> okay, i just did what you said, when i got to the states tab and selected all lights off, it didnt work, and neither did the steps after it, throughhout the whole process it remained at reactive red

Can you provide screenshots of the about?

**Comment by ahaarij** [comment]
<img width="258" alt="Screenshot 2024-03-03 at 1 23 34 PM" src="https://github.com/stickoking/razer-macos/assets/141050074/422d3e00-fdfe-4d8f-8374-8fe670299bd6">


after clearing all settings ^

<img width="495" alt="Screenshot 2024-03-03 at 1 24 07 PM" src="https://github.com/stickoking/razer-macos/assets/141050074/0819b7c9-068a-4e18-b5d0-c144b0df1977">


settings states to all lights off ^^^



<img width="478" alt="Screenshot 2024-03-03 at 1 24 40 PM" src="https://github.com/stickoking/razer-macos/assets/141050074/6def6fb3-f322-4772-b555-c819c053cc4b">


current devices state after changing to lights of ^^^

<img width="268" alt="Screenshot 2024-03-03 at 1 25 43 PM" src="https://github.com/stickoking/razer-macos/assets/141050074/02c4bea3-23ac-46d5-ae0c-04b262264bf7">


device state after changing to spectrum. (not showing on my mouse)

**Comment by stickoking** [comment]
@ahaarij  if you try any setting other than spectrum none works as well? the version of razer-macos is 0.4.13?

**Comment by ahaarij** [comment]
nothing else works, and yes the version is 0.4.13

**Comment by ahaarij** [comment]
im assuming theres a file responsible for changing the properties of the mouse, if so, can i know which one? i tried looking through the apps open files and ports but couldnt find much

**Comment by stickoking** [comment]
> im assuming theres a file responsible for changing the properties of the mouse, if so, can i know which one? i tried looking through the apps open files and ports but couldnt find much

no these are done on driver level if you want to know how it works you can look at the drivers here  https://github.com/stickoking/librazermacos. These are based of openrazer.

**Comment by ahaarij** [comment]
i fixed the error simply by

using a windows laptop, building a profile onto the mouse using synapse 3, and then changing profiles on my mac, the old profile still has the glitch but now the mouse is as i want it. Thanks

**Comment by stickoking** [comment]
> i fixed the error simply by
> 
> using a windows laptop, building a profile onto the mouse using synapse 3, and then changing profiles on my mac, the old profile still has the glitch but now the mouse is as i want it. Thanks

Awesome thanks for informing me. I will close this issue then
